// build.js — Generates config.js from environment variables (for Vercel deployment)
const fs = require('fs');
const path = require('path');

const binId = process.env.JSONBIN_BIN_ID;
const apiKey = process.env.JSONBIN_API_KEY;

if (!binId || !apiKey) {
  console.error(
    'ERROR: Missing required environment variables.\n' +
    'Set JSONBIN_BIN_ID and JSONBIN_API_KEY in your Vercel project settings\n' +
    '(Settings → Environment Variables).'
  );
  process.exit(1);
}

const config = [
  '// Auto-generated by build.js — do not edit manually',
  'const JSONBIN_BIN_ID = ' + JSON.stringify(binId) + ';',
  'const JSONBIN_API_KEY = ' + JSON.stringify(apiKey) + ';',
  ''
].join('\n');

fs.writeFileSync(path.join(__dirname, 'config.js'), config);
console.log('config.js generated successfully.');
